import Badge from "../common/Badge";
import Card from "../common/Card";
import EmptyState from "../common/EmptyState";
import type { PredictionHistoryEntry } from "../../types/prediction";
import type { AgentAnalysisResponse } from "../../types/agent";
import { agreement, isAttack, nextAction, riskLevel } from "../../utils/flowInsights";

interface LiveLogTableProps { entries: PredictionHistoryEntry[]; driftDetected?: boolean; latestAnalysis?: AgentAnalysisResponse | null; }
const displayTimestamp = (timestamp: string) => new Date(timestamp).toLocaleString();
const riskVariant = (risk: string) => risk === "CRITICAL" || risk === "HIGH" ? "danger" : risk === "MEDIUM" ? "warning" : "success";

export default function LiveLogTable({ entries, driftDetected, latestAnalysis }: LiveLogTableProps) {
  return <Card className="mt-6 overflow-hidden p-0 hover:translate-y-0"><div className="flex items-start justify-between gap-4 border-b border-white/5 px-6 py-5"><div><p className="text-sm text-slate-400">Live activity</p><h2 className="mt-1 text-xl font-semibold text-white">What is happening on your network</h2><p className="mt-1 text-xs text-slate-500">Each row is one recent connection checked by the security system.</p></div><span className="rounded-full bg-sky-500/10 px-3 py-1 text-xs font-medium text-sky-400">LIVE</span></div>
    {entries.length === 0 ? <div className="p-6"><EmptyState title="No connections checked yet" description="As soon as the system sees network traffic, simple results and next steps will appear here." /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="bg-slate-900/50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-6 py-4 font-medium">Connection</th><th className="px-6 py-4 font-medium">Time checked</th><th className="px-6 py-4 font-medium">Overall result</th><th className="px-6 py-4 font-medium">AI check 1</th><th className="px-6 py-4 font-medium">AI check 2</th><th className="px-6 py-4 font-medium">Do they agree?</th><th className="px-6 py-4 font-medium">Risk</th><th className="px-6 py-4 font-medium">What you should do</th>{driftDetected !== undefined && <th className="px-6 py-4 font-medium">Traffic changed?</th>}</tr></thead><tbody className="divide-y divide-white/5 text-slate-300">{entries.map((entry) => { const attack = isAttack(entry.hybrid_prediction); const agreed = agreement(entry); const agent = String(latestAnalysis?.flow_id) === String(entry.flow_id) ? latestAnalysis?.analysis : null; const risk = agent?.severity?.toUpperCase() || riskLevel(entry); return <tr key={`${entry.flow_id}-${entry.observedAt}`} className="transition-colors hover:bg-white/[0.02]"><td className="px-6 py-4 font-mono text-xs text-sky-300">#{entry.flow_id}</td><td className="px-6 py-4 whitespace-nowrap text-slate-400">{displayTimestamp(entry.observedAt)}</td><td className="px-6 py-4"><Badge text={attack ? "NEEDS REVIEW" : "LOOKS NORMAL"} variant={attack ? "danger" : "success"} /></td><td className="px-6 py-4">{isAttack(entry.xgb_prediction) ? "Attack likely" : "Looks normal"} <span className="text-xs text-slate-500">({(entry.xgb_probability * 100).toFixed(1)}%)</span></td><td className="px-6 py-4">{isAttack(entry.isolation_prediction) ? "Unusual traffic found" : "Looks normal"}</td><td className="px-6 py-4"><Badge text={agreed ? "YES" : "NO — REVIEW"} variant={agreed ? "success" : "warning"} /></td><td className="px-6 py-4"><Badge text={risk} variant={riskVariant(risk)} /></td><td className="max-w-72 px-6 py-4 text-xs leading-5 text-slate-300">{agent?.incident_report?.recommended_next_step || agent?.recommended_mitigation?.[0] || nextAction(entry)}</td>{driftDetected !== undefined && <td className="px-6 py-4"><Badge text={driftDetected ? "YES — CHECK" : "NO"} variant={driftDetected ? "warning" : "success"} /></td>}</tr>; })}</tbody></table></div>}
  </Card>;
}
